export const isNumber = () => {}
export const isInteger = () => {}
export const isDecimal = () => {}
export const isEmpty = () => {}
export const isEmail = () => {}
export const isIdCardNumber = () => {}
export const isPhoneNumber = () => {}
export const isTelephoneNumber = () => {}
export const isDate = () => {}
export const isDateTime = () => {}
export const isTime = () => {}
